services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_service
    restart: unless-stopped
    
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://192.168.0.200/prometheus/'
      - '--web.route-prefix=/prometheus/'
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=https://192.168.0.200/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - monitor-net

  nginx:
    image: nginx:latest
    container_name: nginx_service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
  
      - /home/webadmin/monitoring-stack/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/webadmin/monitoring-stack/certs:/etc/nginx/ssl:ro
      - /var/www/html:/usr/share/nginx/html:ro
    networks:
      - monitor-net
    depends_on:
      - grafana
      - prometheus

networks:
  monitor-net:
    driver: bridge
